name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        options:
          - patch
          - minor
          - major
        description: "Release type"
        required: true
        default: "minor"

env:
  FORCE_COLOR: 2
  NODE: 20.x

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE }}"
          registry-url: "https://registry.npmjs.org"

      - name: Configure CI Git User
        run: |
          git config user.name pluslabeplus
          git config user.email pluslab@agenciaeplus.com.br

      - name: Bump Minor Version
        run: npm version ${{ github.event.inputs.releaseType }}

      - name: Git Push
        run: |
          git push